### PR TITLE
Added Svelte snippets

### PR DESCRIPTION
**Pull request by ismaeldevmw**
I added a set of popular snippets, however in another set it could include snippets of saper.

### CODE REVIEW

**Comment by lnikell** [comment]
Hi @ismaeldevmw thank you for your contribution! I checked snippets and there are some bugs related to scope. Svelte acts similar to Vue, so inside the file you have <script></script>, <style></style> tags. So to be able to use snippets related to javascript inside <script> you have to use `javascript` scope, and `css` for <style>. And leave scope 'svelte' only for snippets that create general file constuction like "svelte tag script".

**Comment by ismaeldevmw** [comment]
Oh It's true, I will review it, thanks @lnikell

**Comment by lnikell** [comment]
Big thank you for the contribution! Very nice collection of snippets. I've never heard about Svelte before, so thank you for extending my knowledge in this area :) I made some minor adjustments and merged it, I hope you don't mind. If you think there is anything we should change, just let us know.

**Comment by lnikell** [comment]
@ismaeldevmw fixed, thank you!

**Pull request merged**
