### PR TITLE
Added Cypress snippets

### PR DESCRIPTION
**Pull request by vdeantoni**
Added snippets for some of the most used cy.* functions

### CODE REVIEW

**Comment by lnikell** [comment]
@vdeantoni Thank you, great job! Could you add please also require/import snippet?
I will review snippets carefully shortly.

**Comment by lnikell** [comment]
I checked documentation of cypress, so you were right with your snippets. I did not find any use of require('cypress') or something like this. 
Very well done! Nice snippets and descriptions! 
Since it's already merged you can start using it with Snipsnap.

**Comment by vdeantoni** [comment]
Awesome, thank you! I'll probably add more in the future as I replace my snippet extensions with Snipsnap.

**Comment by lnikell** [comment]
@vdeantoni sounds great! Thank you!

**Pull request merged**
